### ISSUE TITLE
Checkmark in menu of all lists after declaring list 'private'

### ISSUE THREAD

**Issue by jniggemann** [alex-LE/yourTinyTodo#64]
applies to current dev:
Admin sets one list of n to private.
After this, context menu of all lists has a checkmark next to private, even if they're not.

**Comment by alex-LE** [comment]
Fixed - this happend because of the disabled multi user feature

**Comment by jniggemann** [comment]
Not quite fixed, problem persists, applies to current dev:
do fresh install from dev
enable multiuser
login as admin
Set one list of n to private
After this, context menu of all lists has a checkmark next to private, even if they're not.
Logout, login as admin
Now click any of the non-private lists and the checkmark isn't displayed (like it should be)
Click on the private list (checkmark is there)
Click on a non-private list: checkmark remains

**Comment by alex-LE** [comment]
ok i will recheck it

**Comment by electricmessiah** [comment]
Confirmed that this problem still exists

**Comment by alex-LE** [comment]
fixed

**Comment by jniggemann** [comment]
Fix confirmed, thank you!
